# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"\x16\n\x04User\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"7\n\x0cNotification\x12\x16\n\x0enotificationId\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"6\n\x13NotificationRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb9\x01\n\x13NotificationService\x12M\n\x17SubscribeToNotification\x12\x12.notification.User\x1a\x1a.notification.Notification\"\x00\x30\x01\x12S\n\x10SendNotification\x12!.notification.NotificationRequest\x1a\x1a.notification.Notification\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=36
  _globals['_USER']._serialized_end=58
  _globals['_NOTIFICATION']._serialized_start=60
  _globals['_NOTIFICATION']._serialized_end=115
  _globals['_NOTIFICATIONREQUEST']._serialized_start=117
  _globals['_NOTIFICATIONREQUEST']._serialized_end=171
  _globals['_NOTIFICATIONSERVICE']._serialized_start=174
  _globals['_NOTIFICATIONSERVICE']._serialized_end=359
# @@protoc_insertion_point(module_scope)
