# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notification_pb2 as notification__pb2


class NotificationServiceStub(object):
    """service streaming RPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeToNotification = channel.unary_stream(
                '/notification.NotificationService/SubscribeToNotification',
                request_serializer=notification__pb2.User.SerializeToString,
                response_deserializer=notification__pb2.Notification.FromString,
                )
        self.SendNotification = channel.unary_unary(
                '/notification.NotificationService/SendNotification',
                request_serializer=notification__pb2.NotificationRequest.SerializeToString,
                response_deserializer=notification__pb2.Notification.FromString,
                )


class NotificationServiceServicer(object):
    """service streaming RPC
    """

    def SubscribeToNotification(self, request, context):
        """the client send a userId and the server responds with a stream of notifications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNotification(self, request, context):
        """the client sends a notification request and the server responds with a notification
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeToNotification': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToNotification,
                    request_deserializer=notification__pb2.User.FromString,
                    response_serializer=notification__pb2.Notification.SerializeToString,
            ),
            'SendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotification,
                    request_deserializer=notification__pb2.NotificationRequest.FromString,
                    response_serializer=notification__pb2.Notification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """service streaming RPC
    """

    @staticmethod
    def SubscribeToNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/notification.NotificationService/SubscribeToNotification',
            notification__pb2.User.SerializeToString,
            notification__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/SendNotification',
            notification__pb2.NotificationRequest.SerializeToString,
            notification__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
